spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/room_genius

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    user: postgres
    password: password

server:
  port: 8223
